name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16.x'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn format:check

      - name: Lint
        run: yarn lint --quiet

      - name: Test
        run: yarn jest
